<%@ Page Language="VB" AutoEventWireup="false" CodeFile="AddItemListFly.aspx.vb" Inherits="AddItemListFly" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>登錄</title>

    <script language="javascript" type="text/javascript">
		function calendarPicker(strField)
		{
			window.open('DatePicker1.aspx?field=' + strField,'calendarPopup','width=250,height=190,resizable=yes');
		}
        			
       function GetExpItem()
       {
            window.open('ExpItemList.aspx','Popup','status=0,toolbar=0,width=580,height=350,top=10,resizable=yes');
       }
        			
		function GetRemark(strField,strField1)
		{
			window.open('RemarkList.aspx?field=' + strField +'&field1='+ strField1,'Popup','width=600,height=350,top=10,resizable=yes');
		}
        			
       function GetReference()
       {
            window.open('ReferenceList.aspx','Popup','status=0,toolbar=0,width=700,height=400,top=10,resizable=yes');
       }
	</script>
</head>
<body>
    <form id="Form1" runat="server">
    <div>
        <!-- -->
        <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
        <!-- ++  底圖                                                                                ++ -->
        <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
        &nbsp;<!-- --><!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ --><!-- ++  Date                                                                            ++ -->
        <input id="BSDate" runat="server" style="z-index: 121; left: 256px; width: 24px;
            position: absolute; top: 136px" type="button" value="..." />
        <asp:TextBox ID="DSDate" runat="server" BackColor="GreenYellow" BorderStyle="Groove" ForeColor="Blue"
            Height="18px" Style="z-index: 100; left: 160px; position: absolute; top: 136px" Width="80px" AutoPostBack="True"></asp:TextBox>
        &nbsp;<!-- ++  ExpItem                                                                             ++ -->
        &nbsp;

        <!-- ++  稅                                                                       ++ -->
        <asp:DropDownList style="Z-INDEX: 102; LEFT: 168px; POSITION: absolute; TOP: 72px" id="DPay" runat="server" Width="104px"  BackColor="GreenYellow" AutoPostBack="True">
        </asp:DropDownList>
        &nbsp;&nbsp;&nbsp;<!-- ++  總額                                                                            ++ -->
        <!-- ++  內容                                                                            ++ -->
        &nbsp;<!-- ++  稅額                                                                            ++ -->&nbsp;<!-- ++  淨額                                                                            ++ -->
        <!-- ++  備註                                                                            ++ -->
        &nbsp; &nbsp;<!-- ------------------------------------------------------------------------------------------ --><!-- ++  表格 ++ -->
        <input id="BADD" runat="server" style="z-index: 116; left: 672px; width: 136px;
            position: absolute; top: 104px; height: 56px " type="button" value="登錄" />
        <input id="BClose" runat="server" style="z-index: 115; left: 976px; width: 136px;
            position: absolute; top: 104px; height: 56px " type="button" value="完成" />
        &nbsp;<!-- ------------------------------------------------------------------------------------------ --><!-- ++  連結 ++ -->
        <asp:TextBox ID="DACID" runat="server" BackColor="White" BorderStyle="None" ForeColor="White"
            Height="24px" Style="z-index: 109; left: 1608px; position: absolute; top: 176px"
            Width="142px"></asp:TextBox>
        &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="DExpItem1" runat="server" BackColor="White" BorderStyle="None" ForeColor="White"
            Height="24px" Style="z-index: 110; left: 1608px; position: absolute; top: 128px"
            Width="142px"></asp:TextBox>
        <asp:TextBox ID="DContent1" runat="server" BackColor="White" BorderStyle="None" ForeColor="White"
            Height="24px" Style="z-index: 111; left: 1608px; position: absolute; top: 72px"
            Width="448px"></asp:TextBox>
      
        &nbsp;
        <asp:Panel ID="Panel2" runat="server" BorderWidth="1px" Height="320px" ScrollBars="Auto"
            Style="left: 32px; position: absolute; top: 184px; z-index: 113;" Width="1304px">
            &nbsp;&nbsp;
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
            BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px"
            CellPadding="3" DataKeyNames="Unique_ID" Font-Size="9pt" ForeColor="Black" GridLines="Vertical"
            Style="z-index: 103; left: 8px; position: absolute; top: 16px" PageSize="100" AutoGenerateSelectButton="True">
            <Columns>
                <asp:BoundField DataField="Unique_ID" HeaderText="ID">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="100px" />
                </asp:BoundField>
                <asp:BoundField DataField="FlyType" HeaderText="類別">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="100px" />
                </asp:BoundField>
                <asp:BoundField DataField="Pay" HeaderText="支付">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="50px" />
                </asp:BoundField>
                <asp:BoundField DataField="Currency1" HeaderText="幣別">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="50px" />
                </asp:BoundField>
                <asp:BoundField DataField="Money1" HeaderText="金額">
                    <ItemStyle Width="100px" />
                </asp:BoundField>
                <asp:BoundField DataField="sDate" HeaderText="收據日期">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="100px" />
                </asp:BoundField>
                <asp:BoundField DataField="SNo" HeaderText="收據單號">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="100px" />
                </asp:BoundField>
                <asp:BoundField DataField="Remark1" HeaderText="備考">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="200px" />
                </asp:BoundField>
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" HorizontalAlign="Center"
                VerticalAlign="Middle" />
            <AlternatingRowStyle BackColor="#CCCCCC" />
        </asp:GridView>
        </asp:Panel>
        &nbsp;&nbsp;
        <asp:Image ID="Image1" runat="server" ImageUrl="~/images/AddFly.jpg" Style="z-index: 99;
            left: 8px; position: absolute; top: 16px" />
        &nbsp;
        <asp:TextBox ID="DRemark1" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" Style="z-index: 101; left: 416px; position: absolute;
            top: 136px" Width="232px"></asp:TextBox>
        <asp:TextBox ID="DMoney1" runat="server" BackColor="GreenYellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" onkeyup="if(isNaN(value))execCommand('undo')"
            Style="z-index: 101; left: 32px; position: absolute; top: 136px" Width="104px"></asp:TextBox>
        <asp:TextBox ID="DSNo" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" Style="z-index: 101; left: 288px; position: absolute;
            top: 136px" Width="104px"></asp:TextBox>
        &nbsp; &nbsp; &nbsp;
        &nbsp; &nbsp; &nbsp; &nbsp;
        <asp:DropDownList style="Z-INDEX: 102; LEFT: 296px; POSITION: absolute; TOP: 72px" id="DCurrency1" runat="server" Width="104px"  BackColor="GreenYellow" AutoPostBack="true">
        </asp:DropDownList>
        &nbsp; &nbsp;
        &nbsp; &nbsp;
        <input id="BReference" runat="server" style="z-index: 133; left: 672px; width: 136px;
            position: absolute; top: 16px; height: 56px" type="button" value="機票款參照" visible="false" />
        &nbsp;
        <input id="BEDIT" runat="server" style="z-index: 116; left: 824px; width: 136px;
            position: absolute; top: 104px; height: 56px " type="button" value="修改" />
        <asp:DropDownList style="Z-INDEX: 102; LEFT: 40px; POSITION: absolute; TOP: 72px" id="DFlyType" runat="server" Width="104px"  BackColor="GreenYellow" AutoPostBack="True">
        </asp:DropDownList>
        <asp:TextBox ID="DID" runat="server" BackColor="White" BorderStyle="None" ForeColor="Blue"
            Height="18px" onkeyup="if(isNaN(value))execCommand('undo')" Style="z-index: 101;
            left: 1624px; position: absolute; top: 248px" Width="72px"></asp:TextBox>
    </div>
    </form>
</body>
</html>
