Imports System.Data
Imports System.Drawing
Imports System.Data.OleDb
Imports System.Data.SqlClient
Imports System.Collections.Generic
Imports System.Windows.Forms
Imports System.Windows

Partial Class AddItemList
    Inherits System.Web.UI.Page

    Dim FieldName(60) As String     '各欄位
    Dim Attribute(60) As Integer    '各欄位屬性    
    Dim Top As String               '預設的控制項位置
    Dim wFormNo As String           '表單號碼
    Dim wFormSno As Integer         '表單流水號
    Dim wStep As Integer            '工程代碼
    Dim wbFormSno As Integer        '連續起單-表單流水號
    Dim wbStep As Integer           '連續起單-工程代碼
    Dim wSeqNo As Integer           '序號
    Dim wApplyID As String          '申請者ID
    Dim wAgentID As String          '被代理人ID
    Dim NowDateTime As String       '現在日期時間
    Dim wNextGate As String         '下一關人
    Dim wOKSts As Integer = 1
    Dim wNGSts1 As Integer = 1
    Dim wNGSts2 As Integer = 1
    '群組行事曆
    Dim wApplyCalendar As String = ""       '申請者
    Dim wDecideCalendar As String = ""      '核定者
    Dim wNextGateCalendar As String = ""    '下一核定者
    Dim wUserName As String = ""            '姓名代理用
    Dim YKK As New YKK_SPDClass   'YKK SPD系共通涵式
    Dim fpObj As New ForProject     '操作db的物件
    Dim uDataBase As Utility.DataBase = fpObj.GetDataBaseObj()
    Dim uCommon As New Utility.Common
    Dim uJavaScript As New Utility.JScript
    Dim oCommon As New Common.CommonService
    Dim oFlow As New Flow.FlowService
    Dim oSchedule As New Schedule.ScheduleService
    Dim remark1, remark2 As String
    Dim DTNo As String
    Dim Days As String
    Dim DTTable As String
    Dim DTTempTable As String
    Dim DTTable1 As String

    '---------------------------------------------------------------------------------------------------
    '*****************************************************************
    '**
    '*****************************************************************

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Dim Errcode As Integer = 0
        Dim Message As String = ""



        BApproveNo.Attributes("onclick") = "GetApproveNo();"

        BOldToNewNo.Attributes("onclick") = "GetOldToNewNo();"

        'DTNo = NowDateTime
        ' DTNo = "23030908302001"

        Days = Request.QueryString("pDays")
        wStep = Request.QueryString("pwStep")
        DTNo = Request.QueryString("pDTNo")
        wFormNo = Request.QueryString("pwFormNo")

        If wFormNo = "008002" Then
            DTTable = " F_QASheetDT "
            DTTable1 = "F_QASheetDT"
            DTTempTable = "F_QASheetDTTemp"
        Else
            DTTable1 = "F_QAmodSheetDT"
            DTTable = "  (select b.* from F_QASheet a, F_QASheetDT b"
            DTTable = DTTable + " where a.no =b.no and a.sts in(1,0))a "

            DTTempTable = "F_QAmodSheetDTTemp"
        End If
 

       

        If Not Me.IsPostBack Then   '不是PostBack
            If wFormNo = "008003" Then
                DResult1.Visible = True
                DResult2.Visible = True
                DResult1.BackColor = Color.Yellow
                DElement.Visible = True
                DQCRemark.Visible = True
                GridView1.AutoGenerateSelectButton = True
                GridView1.AutoGenerateDeleteButton = False

                BEDIT.Visible = False
                BADD.Visible = False
                DSeqNo.Enabled = False
                DSeqNo.BackColor = Color.LightGray
                DElement.Enabled = False
                DElement.BackColor = Color.LightGray
                DResult1.Enabled = False
                DResult1.BackColor = Color.LightGray
                DResult2.Enabled = False
                DResult2.BackColor = Color.LightGray
                DQCRemark.Enabled = False
                DQCRemark.BackColor = Color.LightGray
              
            Else
                DResult1.Visible = False
                DResult2.Visible = False
                DResult1.BackColor = Color.GreenYellow
                DElement.Visible = False
                DQCRemark.Visible = False
                GridView1.AutoGenerateSelectButton = True
                GridView1.AutoGenerateDeleteButton = True

                BEDIT.Visible = False
                BADD.Visible = True
                DSeqNo.Enabled = True
                If wStep = 20 Then
                    DElement.Enabled = True
                    DResult1.Enabled = True
                    DResult2.Enabled = True
                Else
                    DElement.Enabled = False
                    DElement.BackColor = Color.LightGray
                    DResult1.Enabled = False
                    DResult1.BackColor = Color.LightGray
                    DResult2.Enabled = False
                    DResult2.BackColor = Color.LightGray
                    DQCRemark.Enabled = False
                    DQCRemark.BackColor = Color.LightGray

                End If

                
            End If

            SetFieldData()

            GetData()
        Else
            If DOldNO.Text <> "" Then
                DOldToNewNo.Text = DOldNO.Text
            End If
            If DAppNO.Text <> "" Then
                DApproveNo.Text = DAppNO.Text
            End If

        End If






        '
    End Sub


    Protected Sub BADD_ServerClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles BADD.ServerClick

        Dim SQL As String = ""
        Dim haveData As Integer = 0
        Dim StrContains As String = ""
        Dim message As String = ""
        Dim Pullertxt As String = ""
        Dim xShortCat As String = ""

        '20240119 JESSICA 檢查是KEY 簡稱SHORT
        '20240305 JOY 檢查是KEY 簡稱SHORT
        '20240307 SHORT 增加限用 (SPD, EDX專用)
        SQL = " select * from V_PullerShort where short like '%/" + DPuller.Text + "/%'"
        Dim dtPuller As DataTable = uDataBase.GetDataTable(SQL)
        If dtPuller.Rows.Count > 0 Then
            Pullertxt = dtPuller.Rows(0).Item("Puller")
            xShortCat = dtPuller.Rows(0).Item("Buyer")
        Else
            Pullertxt = DPuller.Text
        End If

        '20240119 JESSICA ISIP CODE MASTER 及外注開發存在
        SQL = " select * from M_PullerColor"
        If xShortCat = "SPD" Then
            SQL = SQL + " where puller+color ='" + Trim(DPuller.Text) + Trim(DColor.Text) + "'"
        Else
            SQL = SQL + " where puller+color ='" + Trim(Pullertxt) + Trim(DColor.Text) + "'"
        End If
        Dim dtPullerColor As DataTable = uDataBase.GetDataTable(SQL)
        If dtPullerColor.Rows.Count > 0 Then
            SQL = " select * from F_ManufOutSheet "

            '20240318 JOY A ISIP CODE MASTER 及外注開發存在
            SQL = SQL + " WHERE STS =1 AND SliderGrCode Like'%" + Trim(Pullertxt) + "%'"
            'If xShortCat = "SPD" Then
            '    SQL = SQL + " WHERE STS =1 AND SliderGrCode Like'%" + Trim(Pullertxt) + "%'"
            'Else
            '    SQL = SQL + " WHERE STS =1 AND SliderGrCode Like'%" + Trim(Pullertxt) + "%'"
            'End If

            Dim dtManufOutSheet As DataTable = uDataBase.GetDataTable(SQL)
            If dtManufOutSheet.Rows.Count > 0 Then
            Else
                haveData = 1
                message = "外注開發不存在或開發尚未完成"
            End If
        Else
            haveData = 1
            message = "ISIP CODE MASTER不存在"
        End If


        '先檢查Seqno 有沒有重覆

        If haveData = 0 Then
            SQL = "  select 'No重覆'  as aMessage from  " + DTTempTable + " where no ='" + DTNo + "'"
            SQL = SQL + "  and seqno  = '" + DSeqNo.Text.ToUpper + "'"
            SQL = SQL + "  UNION ALL"
            SQL = SQL + "  select '外注廠+puller+color不可重複'   as aMessage   from " + DTTable + " where len(no)=10  "
            SQL = SQL + "  AND Oldcancel = 0 and SUPPLiER ='" + DSupplier.SelectedValue + "' AND PULLER ='" + Trim(DPuller.Text) + "'  AND COLOR = '" + Trim(DColor.Text) + "'" '
            'ADD-START BY JOY 240520
            SQL = SQL + " AND (SELECT STS FROM F_QASheet WHERE NO=F_QASheetDT.NO) IN ('0','1')"
            'ADD-END
            SQL = SQL + "  UNION ALL "
            SQL = SQL + "  select '外注廠+puller+color不可重複'   as aMessage   from " + DTTempTable + " where  NO ='" + DTNo + "'"
            SQL = SQL + "  AND SUPPLiER ='" + DSupplier.SelectedValue + "' AND PULLER ='" + Trim(DPuller.Text) + "'  AND COLOR = '" + Trim(DColor.Text) + "'" '
            SQL = SQL + "  union all "
            SQL = SQL + "  SELECT '外注廠+puller+color不可重複'   as aMessage from  M_SPDIRWEDX"
            SQL = SQL + "  where   partner ='" + DSupplier.SelectedValue + "' AND PULLER ='" + Trim(DPuller.Text) + "'  AND COLOR = '" + Trim(DColor.Text) + "'" '

            'MsgBox(SQL)
            Dim dtData As DataTable = uDataBase.GetDataTable(SQL)
            '檢查PULLER 有沒有PL-
            If dtData.Rows.Count > 0 Then

                haveData = 1
                message = dtData.Rows(0).Item("aMessage")


                If dtData.Rows(0).Item("aMessage") = "外注廠+puller+color不可重複" Then

                    If DType.SelectedValue = "RENEW" Then '先檢查是不是舊換新
                        '   Dim Result As DialogResult = MessageBox.Show(dtData.Rows(0).Item("aMessage") + "，確定要新增！", "外注廠+puller+color重複", MessageBoxButtons.OKCancel)
                        If DRemark.Text <> "" And DOldToNew.Checked = True Then  '舊換新NO+備註+舊換新 要輸入
                            haveData = 0
                            'If Result = DialogResult.OK Then
                            '    haveData = 0
                            'ElseIf Result = DialogResult.Cancel Then
                            '    haveData = 1
                            'End If
                        Else
                            If DRemark.Text = "" Then
                                message = "請輸入備註！"
                            Else
                                message = "舊廢除請打勾！"
                            End If

                            haveData = 1
                        End If
                    ElseIf DType.SelectedValue = "NEW" Then
                        haveData = 0
                    End If


                End If


            Else
                If DType.SelectedValue = "NEW" Then
                    haveData = 1
                    message = "無新開發資料，請再確認！"
                End If
            End If
        End If





        If haveData = 0 Then
            If InputDataOK(0) Then
                SQL = " Insert into " + DTTempTable + " (No,SeqNo,Type,Supplier,Code,Size,Family,Body,Puller,COLOR,Finish,ApproveNo,OldToNewNo,OldToNew,Remark,Element,Result1,Result2,QCRemark,Createuser,CreateTime,ModifyUser,ModifyTime) "
                SQL = SQL & "VALUES( "
                SQL = SQL & " '" & DTNo & "', "
                SQL = SQL & " N'" & Trim(DSeqNo.Text.ToUpper) & "', "
                SQL = SQL & " '" & DType.SelectedItem.Text & "', "
                SQL = SQL & " '" & DSupplier.SelectedItem.Text & "', "
                SQL = SQL & " N'" & Trim(DCode.Text) & "', "
                SQL = SQL & " N'" & Trim(DSize.SelectedItem.Text) & "', "
                SQL = SQL & " N'" & Trim(DFamily.Text.ToUpper) & "', "
                SQL = SQL & " N'" & Trim(DBody.Text.ToUpper) & "', "
                SQL = SQL & " N'" & Trim(DPuller.Text.ToUpper) & "', "
                SQL = SQL & " N'" & Trim(DColor.Text.ToUpper) & "', "
                SQL = SQL & " N'" & Trim(DFinish.Text.ToUpper) & "', "
                SQL = SQL & " N'" & Trim(DApproveNo.Text.ToUpper) & "', "
                SQL = SQL & " N'" & Trim(DOldToNewNo.Text.ToUpper) & "', "

                If DOldToNewNo.Text = "" Then
                    DOldToNew.Checked = False
                Else
                    DOldToNew.Checked = True
                End If
                If DOldToNew.Checked = True Then
                    SQL = SQL & " 'Yes', "
                Else
                    SQL = SQL & " 'No', "
                End If
                SQL = SQL & " '" & Trim(DRemark.Text.ToUpper) & "', "
                SQL = SQL & " '', "
                SQL = SQL & " '', "
                SQL = SQL & " '', "
                SQL = SQL & " '', "
                SQL = SQL & " '" & Request.QueryString("pUserID") & "', "
                SQL = SQL & " '" & Now.ToString("yyyy/MM/dd HH:mm:ss") & "', "
                SQL = SQL & " '" & Request.QueryString("pUserID") & "', "
                SQL = SQL & " '" & Now.ToString("yyyy/MM/dd HH:mm:ss") & "') "
                uDataBase.ExecuteNonQuery(SQL)
            End If



            SQL = " Select  *   FROM " + DTTempTable + "  where 1=1 "
            SQL = SQL + " and NO = '" + DTNo + "'"
            SQL = SQL + " order by unique_id "


            GridView1.DataSource = uDataBase.GetDataTable(SQL)
            GridView1.DataBind()

        Else

            uJavaScript.PopMsg(Me, message)


        End If



    End Sub

    Sub GetData()
        Dim SQL As String


        SQL = " select * from " + DTTempTable
        SQL = SQL + "  where 1=1 and No='" + DTNo + "'"
        SQL = SQL + " order by seqno "

        GridView1.DataSource = uDataBase.GetDataTable(SQL)
        GridView1.DataBind()

        If wStep <> 1 Then
            SQL = " delete from  " + DTTempTable + "  where no='" + DTNo + "'"
            uDataBase.ExecuteNonQuery(SQL)

            SQL = " Insert into " + DTTempTable + " (No,SeqNo,Type,Supplier,Code,Size,Family,Body,Puller,COLOR,Finish,ApproveNo,OldToNewNo,OldToNew,Remark,Element,Result1,Result2,Createuser,CreateTime,ModifyUser,ModifyTime) "
            SQL = SQL + " select no,SeqNo,Type,Supplier,Code,Size,Family,Body,Puller,COLOR,Finish,ApproveNo,OldToNewNo,OldToNew,Remark,Element,Result1,Result2,"
            SQL = SQL + " '" + Request.QueryString("pUserID") + "',"
            SQL = SQL + " getdate(),'" + Request.QueryString("pUserID") + "',getdate() "
            SQL = SQL + " from  " + DTTable
            SQL = SQL + "  where 1=1 and No='" + DTNo + "' "
            SQL = SQL + " order by SeqNo "
            uDataBase.ExecuteNonQuery(SQL)


        End If



        SQL = " Select  *   FROM " + DTTempTable + "  where 1=1 "
        SQL = SQL + " and NO = '" + DTNo + "'"
        SQL = SQL + " order by seqno "


        GridView1.DataSource = uDataBase.GetDataTable(SQL)
        GridView1.DataBind()



    End Sub

    Protected Sub GridView1_RowCreated(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.GridViewRowEventArgs) Handles GridView1.RowCreated
        e.Row.Cells(1).Visible = False
    End Sub

    Protected Sub GridView1_RowDeleting(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.GridViewDeleteEventArgs) Handles GridView1.RowDeleting
        Dim SQL As String

        Dim id As String = GridView1.DataKeys(e.RowIndex).Value

        SQL = " delete  from   " + DTTempTable
        SQL = SQL & " where unique_id = " & id & " "
        uDataBase.ExecuteNonQuery(SQL)
        '
        DID.Text = ""

        GetData()
    End Sub


    Protected Sub BClose_ServerClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles BClose.ServerClick
        Dim sql As String

        sql = " delete from  " + DTTable1 + " where no='" + DTNo + "'"
        uDataBase.ExecuteNonQuery(sql)

        sql = " Insert into " + DTTable1 + " (No,SeqNo,Type,Supplier,Code,Size,Family,Body,Puller,COLOR,Finish,ApproveNo,OldToNewNo,OldToNew,Remark,Result1,Result2,Createuser,CreateTime,ModifyUser,ModifyTime) "
        sql = sql + " select no,SeqNo,Type,Supplier,Code,Size,Family,Body,Puller,COLOR,Finish,ApproveNo,OldToNewNo,OldToNew,Remark,case when type in ('NEW','REF') THEN 'OK' ELSE Result1 END AS RESULT1,3Result2,"
        sql = sql + " '" + Request.QueryString("pUserID") + "',"
        sql = sql + " getdate(),'" + Request.QueryString("pUserID") + "',getdate() "
        sql = sql + " from  " + DTTempTable
        sql = sql + "  where 1=1 and No='" + DTNo + "' "
        sql = sql + " order by SeqNo "
        uDataBase.ExecuteNonQuery(sql)

     


        Dim js As String = ""
        js &= "window.opener.document.all.DUpdate.value = '1';"
        ' js &= "window.close();"
        js &= "window.opener.document.forms[0].submit();"
        js &= "window.close();"


        '
        Me.ClientScript.RegisterClientScriptBlock(GetType(String), "back", js, True)

        ' 

    End Sub
    '---------------------------------------------------------------------------------------------------
    '*****************************************************************
    '**(FindFieldInf)
    '**     尋找表單欄位屬性
    '**
    '*****************************************************************
    Function FindFieldInf(ByVal pFieldName As String) As Integer
        Dim Run As Boolean
        Dim i As Integer
        Run = True
        FindFieldInf = 9
        While i <= 60 And Run
            If FieldName(i) = pFieldName Then
                FindFieldInf = Attribute(i)
                Run = False
            End If
            i = i + 1
        End While
    End Function



    Function InputDataOK(ByVal pAction As Integer) As Boolean

        Dim Message As String = ""
        Dim isOK As Boolean = False
        Dim ErrCode As Integer = 0   '宣告一個Error用來判別是否資料正常，預設為False




        If ErrCode = 0 Then
            If DSeqNo.Text = "" Then
                ErrCode = 1
            End If
        End If

        If DType.SelectedValue = "REF" Then

            If ErrCode = 0 Then
                If DApproveNo.Text = "" Then
                    ErrCode = 2
                End If
            End If
        End If


        If DType.SelectedValue = "RENEW" Then

            If ErrCode = 0 Then
                If DOldToNewNo.Text = "" Then
                    ErrCode = 3
                End If
            End If
        End If




        If ErrCode = 0 Then
            If DSupplier.SelectedValue = "" Then
                ErrCode = 4
            End If

        End If






        If ErrCode = 1 Then Message = "異常：NO 不能是空值"
        If ErrCode = 2 Then Message = "異常：請選擇共用核可卡"
        If ErrCode = 3 Then Message = "異常：請選擇舊換新"
        If ErrCode = 4 Then Message = "異常：請選擇外注廠商"


        If ErrCode <> 0 Then
            isOK = False
            uJavaScript.PopMsg(Me, Message)

        Else
            isOK = True
        End If

        Return isOK


    End Function



    Protected Sub GridView1_SelectedIndexChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles GridView1.SelectedIndexChanged

        BEDIT.Visible = True
        SetFieldData()
        BADD.Visible = False
        BEDIT.Visible = True

        Dim SQL As String

        Dim id As String = GridView1.SelectedValue


        SQL = " select *,ISNULL(Element,'')Element1  from  " + DTTempTable
        SQL = SQL & " where unique_id = " & id & " "
        Dim dtData As DataTable = uDataBase.GetDataTable(SQL)

        If dtData.Rows(0).Item("Result1") = "OK" Or dtData.Rows(0).Item("Result2") = "OK" Or wFormNo = "008002" Then
            ''
            DSeqNo.Text = dtData.Rows(0).Item("seqno")
            'MODIFY-START JOY 230929
            'DType.SelectedItem.Text = dtData.Rows(0).Item("Type")
            Dim LI1 As ListItem
            LI1 = DType.Items.FindByText(dtData.Rows(0).Item("Type"))
            DType.SelectedIndex = DType.Items.IndexOf(LI1)
            'MODIFY-END JOY 230929
            DSupplier.SelectedValue = dtData.Rows(0).Item("Supplier")
            DCode.Text = dtData.Rows(0).Item("Code")
            DSize.SelectedValue = dtData.Rows(0).Item("Size")
            DFamily.Text = dtData.Rows(0).Item("Family")
            DFinish.Text = dtData.Rows(0).Item("Finish")
            DColor.Text = dtData.Rows(0).Item("Color")
            DPuller.Text = dtData.Rows(0).Item("Puller")
            DBody.Text = dtData.Rows(0).Item("BODY")
            DApproveNo.Text = dtData.Rows(0).Item("ApproveNo")
            DOldToNewNo.Text = dtData.Rows(0).Item("OldToNewNo")


            OldPuller.Text = dtData.Rows(0).Item("Puller")
            OldColor.Text = dtData.Rows(0).Item("Color")
            OldSupplier.Text = dtData.Rows(0).Item("Supplier")

            If dtData.Rows(0).Item("OldToNew") = "Yes" Then
                DOldToNew.Checked = True
            Else
                DOldToNew.Checked = False
            End If
            DRemark.Text = dtData.Rows(0).Item("Remark")
            '  DElement.Text = dtData.Rows(0).Item("Element1")


            'DResult1.SelectedValue = dtData.Rows(0).Item("Result1")
            ' DResult2.SelectedValue = dtData.Rows(0).Item("Result2")
            ' DQCRemark.Text = dtData.Rows(0).Item("QCRemark")


            If dtData.Rows(0).Item("Type") = "REF" And wFormNo = "008002" Then
                DApproveNo.Visible = True
                BApproveNo.Visible = True
            Else
                DApproveNo.Text = ""
                DApproveNo.Visible = False
                BApproveNo.Visible = False
            End If
            If dtData.Rows(0).Item("Type") = "RENEW" And wFormNo = "008002" Then
                DOldToNewNo.Visible = True
                BOldToNewNo.Visible = True
                DOldToNew.Visible = True
            Else
                DOldToNewNo.Text = ""
                DOldToNew.Checked = False
                DOldToNewNo.Visible = False
                BOldToNewNo.Visible = False
                DOldToNew.Visible = False
            End If


            DID.Text = id


        Else
            'DEL-START JOY 230929
            'DSeqNo.Text = ""
            'DType.SelectedItem.Text = ""
            'DSupplier.SelectedValue = ""
            'DCode.Text = ""
            'DSize.SelectedValue = ""
            'DFamily.Text = ""
            'DFinish.Text = ""
            'DColor.Text = ""
            'DBody.Text = ""
            'DApproveNo.Text = ""
            'DOldToNewNo.Text = ""
            'DOldToNew.Checked = False
            'DPuller.Text = ""
            'DRemark.Text = ""
            'DElement.Text = ""
            'DQCRemark.Text = ""
            'DEL-END JOY 230929

            BEDIT.Visible = False
            uJavaScript.PopMsg(Me, "判定OK才可選取！")

        End If


   
      
    End Sub

    Protected Sub BEDIT_ServerClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles BEDIT.ServerClick

        Dim Message As String = ""
        ''預支款自動代入負數
        Dim SQL As String
        Dim haveData As Integer = 0
        Dim StrContains As String = ""
        Dim Pullertxt As String

        '先檢查Seqno 有沒有重覆

        '20240119 JESSICA 檢查是KEY 簡稱SHORT
        SQL = " select * from V_PullerShort where short like '%" + DPuller.Text + "%'"
        Dim dtPuller As DataTable = uDataBase.GetDataTable(SQL)
        If dtPuller.Rows.Count > 0 Then
            Pullertxt = dtPuller.Rows(0).Item("Puller")
        Else
            Pullertxt = DPuller.Text
        End If

        '20240119 JESSICA ISIP CODE MASTER 及外注開發存在
        SQL = " select * from M_PullerColor"
        SQL = SQL + " where puller+color ='" + Trim(Pullertxt) + Trim(DColor.Text) + "'"
        Dim dtPullerColor As DataTable = uDataBase.GetDataTable(SQL)
        If dtPullerColor.Rows.Count > 0 Then
            SQL = " select * from F_ManufOutSheet "
            SQL = SQL + " WHERE STS =1 AND SliderGrCode Like'%" + Trim(DPuller.Text) + "%'"
            Dim dtManufOutSheet As DataTable = uDataBase.GetDataTable(SQL)
            If dtManufOutSheet.Rows.Count > 0 Then
            Else
                haveData = 1
                Message = "外注開發不存在或開發尚未完成"
            End If
        Else
            haveData = 1
            Message = "ISIP CODE MASTER不存在"
        End If


        If haveData = 0 Then
            If wFormNo = "008002" Then

                '先刪除再INSERT 
                SQL = " delete from " + DTTempTable
                SQL = SQL + " where no ='" + DTNo + "' and seqno ='" + DSeqNo.Text + "'"
                uDataBase.ExecuteNonQuery(SQL)

                SQL = "  select '外注廠+puller+color不可重複'   as aMessage   from " + DTTable + " where len(no)=10  "
                SQL = SQL + "  AND Oldcancel = 0 and SUPPLiER ='" + DSupplier.SelectedValue + "' AND PULLER ='" + DPuller.Text + "'  AND COLOR = '" + DColor.Text + "'" '
                SQL = SQL + "  UNION ALL "
                SQL = SQL + "  select '外注廠+puller+color不可重複'   as aMessage   from " + DTTempTable + " where  NO ='" + DTNo + "'"
                SQL = SQL + "  AND SUPPLiER ='" + DSupplier.SelectedValue + "' AND PULLER ='" + DPuller.Text + "'  AND COLOR = '" + DColor.Text + "'" '
                SQL = SQL + "  union all "
                SQL = SQL + "  SELECT '外注廠+puller+color不可重複'   as aMessage from  M_SPDIRWEDX"
                SQL = SQL + "  where   partner ='" + DSupplier.SelectedValue + "' AND PULLER ='" + DPuller.Text + "'  AND COLOR = '" + DColor.Text + "'" '

                Dim dtData As DataTable = uDataBase.GetDataTable(SQL)
                '檢查PULLER 有沒有PL-
                If dtData.Rows.Count > 0 Then
                    haveData = 1
                    Message = dtData.Rows(0).Item("aMessage")

                    If dtData.Rows(0).Item("aMessage") = "外注廠+puller+color不可重複" Then


                        If DType.SelectedValue = "RENEW" Then '先檢查是不是舊換新
                            '   Dim Result As DialogResult = MessageBox.Show(dtData.Rows(0).Item("aMessage") + "，確定要新增！", "外注廠+puller+color重複", MessageBoxButtons.OKCancel)
                            If DRemark.Text <> "" And DOldToNew.Checked = True Then  '舊換新NO+備註+舊換新 要輸入
                                haveData = 0
                                'If Result = DialogResult.OK Then
                                '    haveData = 0
                                'ElseIf Result = DialogResult.Cancel Then
                                '    haveData = 1
                                'End If
                            Else
                                If DRemark.Text = "" Then
                                    Message = "請輸入備註！"
                                Else
                                    Message = "舊廢除請打勾！"
                                End If

                                haveData = 1
                            End If
                        ElseIf DType.SelectedValue = "NEW" Then
                            haveData = 0
                        End If

                    End If
                Else
                    If DType.SelectedValue = "NEW" Then
                        haveData = 1
                        Message = "無新開發資料，請再確認！"
                    End If
                End If



            Else


                '先檢查Seqno 有沒有重覆

                SQL = "  select '外注廠+puller+color不可重複'   as aMessage   from F_QASHEETDT  where "
                SQL = SQL + "  SUPPLiER ='" + DSupplier.SelectedValue + "' AND PULLER ='" + DPuller.Text + "'  AND COLOR = '" + DColor.Text + "'" '
                SQL = SQL + "  UNION ALL "
                SQL = SQL + "  select '外注廠+puller+color不可重複'   as aMessage   from " + DTTempTable + " where  NO ='" + DTNo + "'"
                SQL = SQL + "  AND SUPPLiER ='" + DSupplier.SelectedValue + "' AND PULLER ='" + DPuller.Text + "'  AND COLOR = '" + DColor.Text + "'" '
                SQL = SQL + "  union all "
                SQL = SQL + "  SELECT '外注廠+puller+color不可重複'   as aMessage from  M_SPDIRWEDX"
                SQL = SQL + "  where   partner ='" + DSupplier.SelectedValue + "' AND PULLER ='" + DPuller.Text + "'  AND COLOR = '" + DColor.Text + "'" '
                'MOD-END JOY 230929

                Dim dtData As DataTable = uDataBase.GetDataTable(SQL)
                If dtData.Rows.Count > 0 Then
                    haveData = 1
                    Message = dtData.Rows(0).Item("aMessage")
                    If DType.SelectedValue = "NEW" And dtData.Rows(0).Item("aMessage") = "外注廠+puller+color不可重複" Then
                        haveData = 0
                    ElseIf DType.SelectedValue = "ADD" Then  '20231221  增加ADD可修改如果外注廠+puller+color　沒變
                        If OldSupplier.Text = DSupplier.SelectedValue And OldPuller.Text = DPuller.Text And OldColor.Text = DColor.Text Then
                            haveData = 0
                        End If

                    End If
                Else
                    If DType.SelectedValue = "NEW" Then
                        haveData = 1
                        Message = "無新開發資料，請再確認！"
                    End If
                End If
            End If

        End If




       
        If haveData = 0 Then
            Try

                If DID.Text <> "" Then
                    If InputDataOK(0) Then
                        If wFormNo = "008002" Then


                            SQL = " Insert into " + DTTempTable + " (No,SeqNo,Type,Supplier,Code,Size,Family,Body,Puller,COLOR,Finish,ApproveNo,OldToNewNo,OldToNew,Remark,Element,Result1,Result2,QCRemark,Createuser,CreateTime,ModifyUser,ModifyTime) "
                            SQL = SQL & "VALUES( "
                            SQL = SQL & " '" & DTNo & "', "
                            SQL = SQL & " N'" & Trim(DSeqNo.Text.ToUpper) & "', "
                            SQL = SQL & " '" & DType.SelectedItem.Text & "', "
                            SQL = SQL & " '" & DSupplier.SelectedItem.Text & "', "
                            SQL = SQL & " N'" & Trim(DCode.Text) & "', "
                            SQL = SQL & " N'" & Trim(DSize.SelectedItem.Text) & "', "
                            SQL = SQL & " N'" & Trim(DFamily.Text.ToUpper) & "', "
                            SQL = SQL & " N'" & Trim(DBody.Text.ToUpper) & "', "
                            SQL = SQL & " N'" & Trim(DPuller.Text.ToUpper) & "', "
                            SQL = SQL & " N'" & Trim(DColor.Text.ToUpper) & "', "
                            SQL = SQL & " N'" & Trim(DFinish.Text.ToUpper) & "', "
                            SQL = SQL & " N'" & Trim(DApproveNo.Text.ToUpper) & "', "
                            SQL = SQL & " N'" & Trim(DOldToNewNo.Text.ToUpper) & "', "

                            If DOldToNewNo.Text = "" Then
                                DOldToNew.Checked = False
                            Else
                                DOldToNew.Checked = True
                            End If
                            If DOldToNew.Checked = True Then
                                SQL = SQL & " 'Yes', "
                            Else
                                SQL = SQL & " 'No', "
                            End If
                            SQL = SQL & " '" & Trim(DRemark.Text.ToUpper) & "', "
                            SQL = SQL & " '', "
                            SQL = SQL & " '', "
                            SQL = SQL & " '', "
                            SQL = SQL & " '', "
                            SQL = SQL & " '" & Request.QueryString("pUserID") & "', "
                            SQL = SQL & " '" & Now.ToString("yyyy/MM/dd HH:mm:ss") & "', "
                            SQL = SQL & " '" & Request.QueryString("pUserID") & "', "
                            SQL = SQL & " '" & Now.ToString("yyyy/MM/dd HH:mm:ss") & "') "
                            uDataBase.ExecuteNonQuery(SQL)
                        Else
                            SQL = "  Update  " + DTTempTable
                            SQL = SQL & " set Type =N'" & DType.SelectedItem.Text & "' "
                            SQL = SQL & " ,Supplier =N'" & DSupplier.SelectedItem.Text & "' "
                            SQL = SQL & " ,Code =N'" & DCode.Text.ToUpper & "' "
                            SQL = SQL & " ,Size =N'" & DSize.Text.ToUpper & "'"
                            SQL = SQL & " ,Family =N'" & DFamily.Text.ToUpper & "'"
                            SQL = SQL & " ,Body =N'" & DBody.Text.ToUpper & "'"
                            SQL = SQL & " ,Puller =N'" & DPuller.Text.ToUpper & "'"
                            SQL = SQL & " ,Color =N'" & DColor.Text.ToUpper & "'"
                            SQL = SQL & " ,Finish =N'" & DFinish.Text & "'"
                            SQL = SQL & " ,ApproveNo =N'" & DApproveNo.Text.ToUpper & "'"
                            SQL = SQL & " ,OldToNewNo =N'" & DOldToNewNo.Text.ToUpper & "'"
                            If DOldToNew.Checked = True Then
                                SQL = SQL & " ,OldToNew='Yes'"
                            Else
                                SQL = SQL & " ,OldToNew='No'"
                            End If
                            SQL = SQL & " ,Remark=N'" & DRemark.Text.ToUpper & "' "
                            SQL = SQL & " ,ModifyUser ='" & Request.QueryString("pUserID") & "' "
                            SQL = SQL & " ,ModifyTime ='" & Now.ToString("yyyy/MM/dd HH:mm:ss") & "' "
                            SQL = SQL & " Where seqno ='" & DSeqNo.Text + "'"
                            uDataBase.ExecuteNonQuery(SQL)

                        End If

                        Message = "資料已修改!"

                        'DEL-START JOY 230929
                        'DSeqNo.Text = ""
                        'DType.SelectedItem.Text = ""
                        'DSupplier.SelectedValue = ""
                        'DCode.Text = ""
                        'DSize.SelectedValue = ""
                        'DFamily.Text = ""
                        'DPuller.Text = ""
                        'DFinish.Text = ""
                        'DColor.Text = ""
                        'DBody.Text = ""
                        'DApproveNo.Text = ""
                        'DOldToNewNo.Text = ""
                        'DOldToNew.Checked = False
                        'DRemark.Text = ""
                        'DEL-END JOY 230929
                    End If
                Else
                    Message = "未選取資料!"

                End If

                GridView1.SelectedIndex = -1


                SQL = " Select  *   FROM " + DTTempTable + "  where 1=1 "
                SQL = SQL + " and NO = '" + DTNo + "'"
                SQL = SQL + " order by unique_id "


                GridView1.DataSource = uDataBase.GetDataTable(SQL)
                GridView1.DataBind()

            Catch ex As Exception
                Message = "異常,請連絡系統人員!"

            End Try
        Else
            GridView1.SelectedIndex = -1
            uJavaScript.PopMsg(Me, Message)

        End If
        BEDIT.Visible = False
        If wFormNo = "008002" Then
            BADD.Visible = True
        End If
        'SetFieldData()

    End Sub

    Protected Sub DPay_SelectedIndexChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles DResult1.SelectedIndexChanged
        If DResult1.SelectedValue = "公司卡" Then
            '  DCurrency.Enabled = False
            '  DDays.Enabled = False
            ' DMoney.Enabled = False

            ' DCurrency.BackColor = Color.LightGray
            ' DDays.BackColor = Color.LightGray
            'DMoney.BackColor = Color.LightGray
            'DRate.BackColor = Color.LightGray
        Else
            'DCurrency.Enabled = True
            'DDays.Enabled = True
            'DMoney.Enabled = True

            'DCurrency.BackColor = Color.GreenYellow
            'DDays.BackColor = Color.GreenYellow
            'DMoney.BackColor = Color.GreenYellow
            ' DRate.BackColor = Color.GreenYellow
        End If
    End Sub

    Protected Sub GridView1_RowDataBound(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.GridViewRowEventArgs) Handles GridView1.RowDataBound
        'Dim h1 As New HyperLink
        'Dim sql As String
        'If e.Row.RowType = DataControlRowType.DataRow Then
        '    h1.Text = e.Row.Cells(10).Text
        '    ' 連結到待處理LIST
        '    ' h1.NavigateUrl = "http://10.245.1.10/N2W/ComplaintOutScheduleAll.aspx?&pStep=" + wStep

        '    If h1.Text <> "&nbsp;" Then
        '        sql = " select * from F_ExpenseSheet"
        '        sql = sql + "  where no ='" & DExpenseNo.Text & "'"
        '        Dim Ddata2 As DataTable = uDataBase.GetDataTable(sql)
        '        If Ddata2.Rows.Count > 0 Then

        '            h1.NavigateUrl = "http://10.245.1.10/N2W/ExpenseSheet_02.aspx?pFormNo=003105&pFormSno=" + Trim(Ddata2.Rows(0).Item("formsno"))

        '        End If
        '        h1.Target = "_blank"
        '        e.Row.Cells(10).Text = ""
        '        e.Row.Cells(10).Controls.Add(h1)
        '    End If



        'End If
    End Sub





    '*****************************************************************
    '**(SetFieldData)
    '**     建置下拉式選單初始值
    '**
    '*****************************************************************
    Sub SetFieldData()


        Dim SQL As String
        Dim i As Integer


        '類別
        SQL = "  SELECT   Data   from M_referp  "
        SQL = SQL + " where cat = '8002' and dkey ='Type' order by unique_id    "
        Dim dtReferp1 As DataTable = uDataBase.GetDataTable(SQL)
        DType.Items.Clear()
        DType.Items.Add("")
        For i = 0 To dtReferp1.Rows.Count - 1
            Dim ListItem1 As New ListItem
            ListItem1.Text = dtReferp1.Rows(i).Item("Data")
            ListItem1.Value = dtReferp1.Rows(i).Item("Data")
            DType.Items.Add(ListItem1)
        Next

        DType.Items(3).Selected = True
        dtReferp1.Clear()




        '廠商
        SQL = "  SELECT  Data from M_referp    "
        SQL = SQL + " where cat = '8002' and dkey ='Supplier' order by Data  "
        Dim dtReferp4 As DataTable = uDataBase.GetDataTable(SQL)
        DSupplier.Items.Clear()
        DSupplier.Items.Add("")


        For i = 0 To dtReferp4.Rows.Count - 1
            Dim ListItem1 As New ListItem
            ListItem1.Text = dtReferp4.Rows(i).Item("Data")
            ListItem1.Value = dtReferp4.Rows(i).Item("Data")
            DSupplier.Items.Add(ListItem1)

        Next
        dtReferp4.Clear()



        '判定
        SQL = "  SELECT Data  from M_referp    "
        SQL = SQL + " where cat = '8002' and dkey ='Result1' order by unique_id   "
        Dim dtReferp2 As DataTable = uDataBase.GetDataTable(SQL)
        DResult1.Items.Clear()
        DResult1.Items.Add("")

        For i = 0 To dtReferp2.Rows.Count - 1
            Dim ListItem1 As New ListItem
            ListItem1.Text = dtReferp2.Rows(i).Item("Data")
            ListItem1.Value = dtReferp2.Rows(i).Item("Data")
            DResult1.Items.Add(ListItem1)

        Next
        dtReferp2.Clear()




        '判定
        SQL = "  SELECT Data  from M_referp    "
        SQL = SQL + " where cat = '8002' and dkey ='Result2' order by unique_id   "
        Dim dtReferp3 As DataTable = uDataBase.GetDataTable(SQL)
        DResult2.Items.Clear()
        DResult2.Items.Add("")

        For i = 0 To dtReferp3.Rows.Count - 1
            Dim ListItem1 As New ListItem
            ListItem1.Text = dtReferp3.Rows(i).Item("Data")
            ListItem1.Value = dtReferp3.Rows(i).Item("Data")
            DResult2.Items.Add(ListItem1)

        Next
        dtReferp3.Clear()





        'size
        SQL = "  SELECT Data  from M_referp    "
        SQL = SQL + " where cat = '8002' and dkey ='Size' order by Data  "
        Dim dtReferp5 As DataTable = uDataBase.GetDataTable(SQL)
        DSize.Items.Clear()
        DSize.Items.Add("")

        For i = 0 To dtReferp5.Rows.Count - 1
            Dim ListItem1 As New ListItem
            ListItem1.Text = dtReferp5.Rows(i).Item("Data")
            ListItem1.Value = dtReferp5.Rows(i).Item("Data")
            DSize.Items.Add(ListItem1)

        Next
        dtReferp5.Clear()



        'family
        SQL = "  SELECT Data  from M_referp    "
        SQL = SQL + " where cat = '8002' and dkey ='Family' order by Data  "
        Dim dtReferp6 As DataTable = uDataBase.GetDataTable(SQL)
        DFamily.Items.Clear()
        DFamily.Items.Add("")

        For i = 0 To dtReferp6.Rows.Count - 1
            Dim ListItem1 As New ListItem
            ListItem1.Text = dtReferp6.Rows(i).Item("Data")
            ListItem1.Value = dtReferp6.Rows(i).Item("Data")
            DFamily.Items.Add(ListItem1)

        Next
        dtReferp6.Clear()


        'Body
        SQL = "  SELECT Data  from M_referp    "
        SQL = SQL + " where cat = '8002' and dkey ='Body' order by Data  "
        Dim dtReferp7 As DataTable = uDataBase.GetDataTable(SQL)
        DBody.Items.Clear()
        DBody.Items.Add("")

        For i = 0 To dtReferp7.Rows.Count - 1
            Dim ListItem1 As New ListItem
            ListItem1.Text = dtReferp7.Rows(i).Item("Data")
            ListItem1.Value = dtReferp7.Rows(i).Item("Data")
            DBody.Items.Add(ListItem1)

        Next
        dtReferp7.Clear()




    End Sub


    Protected Sub DOldToNewNo_TextChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles DOldToNewNo.TextChanged
        If DOldToNewNo.Text <> "" Then
            DOldToNew.Checked = True
        Else
            DOldToNew.Checked = False
        End If
    End Sub


    Protected Sub DType_SelectedIndexChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles DType.SelectedIndexChanged
        DOldToNewNo.Text = ""
        DOldNO.Text = ""
        DApproveNo.Text = ""
        DAppNO.Text = ""
        If DType.SelectedValue = "REF" And wFormNo = "008002" Then
            DApproveNo.Visible = True
            BApproveNo.Visible = True
            DApproveNo.ReadOnly = True
        Else
            DApproveNo.Text = ""
            DApproveNo.Visible = False
            BApproveNo.Visible = False
        End If
        If DType.SelectedValue = "RENEW" And wFormNo = "008002" Then
            DOldToNewNo.Visible = True
            BOldToNewNo.Visible = True
            DOldToNew.Visible = True
            DOldToNewNo.ReadOnly = True
        Else
            DOldToNewNo.Text = ""
            DOldToNew.Checked = False
            DOldToNewNo.Visible = False
            BOldToNewNo.Visible = False
            DOldToNew.Visible = False
        End If
    End Sub
End Class
