<%@ Page Language="VB" AutoEventWireup="false" CodeFile="ModItemList.aspx.vb" Inherits="ModItemList" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>登錄</title>

    <script language="javascript" type="text/javascript">
		function calendarPicker(strField)
		{
			window.open('DatePicker1.aspx?field=' + strField,'calendarPopup','width=250,height=190,resizable=yes');
		}
        			
 
        			
       function GetApproveNo()
       {
            window.open('ApproveNoList.aspx','Popup','status=0,toolbar=0,width=1200,height=400,top=10,resizable=yes');
       }
               
               
      function GetOldToNewNo()
       {
            window.open('OldToNewNoList.aspx','Popup','status=0,toolbar=0,width=1200,height=400,top=10,resizable=yes');
       } 			
    
	</script>
</head>
<body>
    <form id="Form1" runat="server">
    <div>
        <!-- -->
        <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
        <!-- ++  底圖                                                                                ++ -->
        <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
        &nbsp;<!-- --><!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ --><!-- ++  Date                                                                            ++ -->
        &nbsp; &nbsp;<!-- ++  ExpItem                                                                             ++ -->
        &nbsp;

        <!-- ++  稅                                                                       ++ -->
        &nbsp;&nbsp;&nbsp;<!-- ++  總額                                                                            ++ -->
        <!-- ++  內容                                                                            ++ -->
        &nbsp;<!-- ++  稅額                                                                            ++ -->&nbsp;<!-- ++  淨額                                                                            ++ -->
        <!-- ++  備註                                                                            ++ -->
        &nbsp; &nbsp;<!-- ------------------------------------------------------------------------------------------ --><!-- ++  表格 ++ -->
        <input id="BADD" runat="server" style="z-index: 125; left: 1064px; width: 88px;
            position: absolute; top: 160px; height: 56px " type="button" value="登錄" />
        <input id="BClose" runat="server" style="z-index: 124; left: 1256px; width: 88px;
            position: absolute; top: 160px; height: 56px " type="button" value="完成" />
        &nbsp;<!-- ------------------------------------------------------------------------------------------ --><!-- ++  連結 ++ -->
        <asp:TextBox ID="DACID" runat="server" BackColor="White" BorderStyle="None" ForeColor="White"
            Height="24px" Style="z-index: 101; left: 1608px; position: absolute; top: 176px"
            Width="142px"></asp:TextBox>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="DExpItem1" runat="server" BackColor="White" BorderStyle="None" ForeColor="White"
            Height="24px" Style="z-index: 102; left: 1608px; position: absolute; top: 128px"
            Width="142px"></asp:TextBox>
        <asp:TextBox ID="DContent1" runat="server" BackColor="White" BorderStyle="None" ForeColor="White"
            Height="24px" Style="z-index: 103; left: 1608px; position: absolute; top: 72px"
            Width="448px"></asp:TextBox>
        <asp:TextBox ID="DRemark1" runat="server" BackColor="White" BorderStyle="None" ForeColor="White"
            Height="24px" Style="z-index: 104; left: 1608px; position: absolute; top: 32px"
            Width="142px"></asp:TextBox>
        &nbsp;
        <asp:Panel ID="Panel2" runat="server" BorderWidth="1px" Height="568px" ScrollBars="Auto"
            Style="left: 32px; position: absolute; top: 232px; z-index: 105;" Width="1304px">
            &nbsp;&nbsp;
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
            BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px"
            CellPadding="3" DataKeyNames="Unique_ID" Font-Size="9pt" ForeColor="Black" GridLines="Vertical"
            Style="z-index: 100; left: 8px; position: absolute; top: 8px" PageSize="100" AutoGenerateSelectButton="True">
            <Columns>
                <asp:BoundField DataField="Unique_ID" HeaderText="ID">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="30px" />
                </asp:BoundField>
                <asp:BoundField DataField="SeqNo" HeaderText="No" />
                <asp:BoundField DataField="Type" HeaderText="類別">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="50px" />
                </asp:BoundField>
                <asp:BoundField DataField="Supplier" HeaderText="廠商" >
                    <ItemStyle Width="50px" />
                </asp:BoundField>
                <asp:BoundField DataField="Code" HeaderText="CODE">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="50px" />
                </asp:BoundField>
                <asp:BoundField DataField="Size" HeaderText="SIZE">
                    <ItemStyle Width="50px" />
                </asp:BoundField>
                <asp:BoundField DataField="Family" HeaderText="FAMILY">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="50px" HorizontalAlign="Left" />
                </asp:BoundField>
                <asp:BoundField DataField="Body" HeaderText="BODY">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="50px" />
                </asp:BoundField>
                <asp:BoundField DataField="Puller" HeaderText="PULLER">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="50px" HorizontalAlign="Left" />
                </asp:BoundField>
                <asp:BoundField HeaderText="COLOR" DataField="Color" />
                <asp:BoundField DataField="Finish" HeaderText="FINISH">
                    <ItemStyle Width="50px" />
                </asp:BoundField>
                <asp:BoundField DataField="ApproveNo" HeaderText="共用核可卡" >
                    <ItemStyle HorizontalAlign="Right" />
                </asp:BoundField>
                <asp:BoundField DataField="OldToNewNo" HeaderText="舊換新NO" />
                <asp:BoundField DataField="OldToNew" HeaderText="舊換新" />
                <asp:BoundField DataField="Element" HeaderText="待判(element)">
                    <ItemStyle Width="100px" />
                </asp:BoundField>
                <asp:BoundField DataField="Result1" HeaderText="EDX判定" />
                <asp:BoundField DataField="Remark" HeaderText="備註">
                    <HeaderStyle Height="20px" />
                    <ItemStyle Width="100px" />
                </asp:BoundField>
                <asp:BoundField DataField="Result2" HeaderText="EDX覆定" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" HorizontalAlign="Center"
                VerticalAlign="Middle" />
            <AlternatingRowStyle BackColor="#CCCCCC" />
        </asp:GridView>
            &nbsp; &nbsp;
        </asp:Panel>
        &nbsp;&nbsp;
        <asp:Image ID="Image1" runat="server" ImageUrl="~/images/AddItem_01.jpg" Style="z-index: 106;
            left: 16px; position: absolute; top: 48px" />
        <asp:TextBox ID="DFINISH" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" Style="z-index: 121; left: 968px; text-transform: uppercase;
            position: absolute; top: 120px" Width="64px"></asp:TextBox>
        <asp:TextBox ID="DElement" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" Style="z-index: 109; left: 464px; text-transform: uppercase;
            position: absolute; top: 184px" Width="232px"></asp:TextBox>
        <asp:DropDownList style="Z-INDEX: 115; LEFT: 144px; POSITION: absolute; TOP: 120px" id="DType" runat="server" Width="96px"  BackColor="Yellow" AutoPostBack="True">
            </asp:DropDownList>
        <asp:TextBox ID="DOldToNewNo" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" Style="z-index: 107; left: 248px; text-transform: uppercase;
            position: absolute; top: 184px" Width="96px"></asp:TextBox>
        <asp:TextBox ID="DApproveNo" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" Style="z-index: 108; left: 40px; text-transform: uppercase;
            position: absolute; top: 184px" Width="168px"></asp:TextBox>
        <input id="BApproveNo" runat="server" style="z-index: 128; left: 216px; width: 24px;
            position: absolute; top: 184px" type="button" value="..." />
        <input id="BOldToNewNo" runat="server" style="z-index: 127; left: 352px; width: 24px;
            position: absolute; top: 184px" type="button" value="..." />
        <asp:TextBox ID="DColor" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" Style="z-index: 109; left: 888px; text-transform: uppercase;
            position: absolute; top: 120px" Width="64px"></asp:TextBox>
        &nbsp; &nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="DCode" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" onkeyup="if(isNaN(value))execCommand('undo')"
            Style="z-index: 112; left: 464px; position: absolute; top: 120px" Width="64px" MaxLength="7"></asp:TextBox>
        <asp:TextBox ID="DPuller" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px"  
            Style="z-index: 113; left: 800px; position: absolute; top: 120px; TEXT-TRANSFORM:   uppercase " Width="64px"></asp:TextBox>
        <asp:TextBox ID="DSeqNo" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px"  
            Style="z-index: 114; left: 40px; position: absolute; top: 120px; TEXT-TRANSFORM:   uppercase " Width="88px"></asp:TextBox>
        <asp:DropDownList style="Z-INDEX: 115; LEFT: 256px; POSITION: absolute; TOP: 120px" id="DSupplier" runat="server" Width="192px"  BackColor="Yellow" AutoPostBack="True">
            </asp:DropDownList>
        &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;
        <asp:TextBox ID="DRemark" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px"
            Style="z-index: 116; left: 888px; position: absolute; top: 184px" Width="144px"></asp:TextBox>
        &nbsp;&nbsp;&nbsp; &nbsp; &nbsp;
        &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
        &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
        <asp:DropDownList style="Z-INDEX: 118; LEFT: 712px; POSITION: absolute; TOP: 184px" id="DResult1" runat="server" Width="72px"  BackColor="Yellow" AutoPostBack="True">
        </asp:DropDownList><asp:DropDownList style="Z-INDEX: 119; LEFT: 792px; POSITION: absolute; TOP: 184px" id="DResult2" runat="server" Width="72px"  BackColor="Yellow" AutoPostBack="True">
        </asp:DropDownList>
        &nbsp; &nbsp;&nbsp;
        <asp:TextBox ID="DID" runat="server" BackColor="White" BorderStyle="None" ForeColor="Blue"
            Height="18px" onkeyup="if(isNaN(value))execCommand('undo')" Style="z-index: 120;
            left: 1624px; position: absolute; top: 248px" Width="72px"></asp:TextBox>
        <input id="BEDIT" runat="server" style="z-index: 126; left: 1160px; width: 88px;
            position: absolute; top: 160px; height: 56px " type="button" value="修改" />
        &nbsp;&nbsp;
        <asp:TextBox ID="DBODY" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" Style="z-index: 121; left: 720px; text-transform: uppercase;
            position: absolute; top: 120px" Width="64px"></asp:TextBox><asp:DropDownList style="Z-INDEX: 122; LEFT: 544px; POSITION: absolute; TOP: 120px" id="DSize" runat="server" Width="72px"  BackColor="Yellow" AutoPostBack="True">
            </asp:DropDownList>
        <asp:CheckBox ID="DOldToNew" runat="server" Style="z-index: 129; left: 384px; position: absolute;
            top: 184px" Width="80px" Text="舊廢除" />
        <asp:TextBox ID="DFamily" runat="server" BackColor="Yellow" BorderStyle="Groove"
            ForeColor="Blue" Height="18px" Style="z-index: 121; left: 632px; text-transform: uppercase;
            position: absolute; top: 120px" Width="64px"></asp:TextBox>
    </div>
    </form>
</body>
</html>
