'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 1.1.4322.2503。
'
Namespace Common
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CommonServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class CommonService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.245.1.50/WFS/CommonService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BatchFlowControl", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BatchFlowControl(ByVal pFun As String, ByVal pAction As Integer, ByVal pSts As String, ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pStep As Integer, ByVal pSeqNo As Integer, ByVal pDecideCalendar As String, ByVal pDecideID As String, ByVal pApplyID As String, ByVal pAgentID As String, ByVal pTableName As String) As Integer
            Dim results() As Object = Me.Invoke("BatchFlowControl", New Object() {pFun, pAction, pSts, pFormNo, pFormSno, pStep, pSeqNo, pDecideCalendar, pDecideID, pApplyID, pAgentID, pTableName})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginBatchFlowControl(ByVal pFun As String, ByVal pAction As Integer, ByVal pSts As String, ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pStep As Integer, ByVal pSeqNo As Integer, ByVal pDecideCalendar As String, ByVal pDecideID As String, ByVal pApplyID As String, ByVal pAgentID As String, ByVal pTableName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("BatchFlowControl", New Object() {pFun, pAction, pSts, pFormNo, pFormSno, pStep, pSeqNo, pDecideCalendar, pDecideID, pApplyID, pAgentID, pTableName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndBatchFlowControl(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMail", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendMail() As Integer
            Dim results() As Object = Me.Invoke("SendMail", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginSendMail(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SendMail", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSendMail(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Send(ByVal pFrom As String, ByVal pTo As String, ByVal pApplyID As String, ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pStep As Integer, ByVal pType As String) As Integer
            Dim results() As Object = Me.Invoke("Send", New Object() {pFrom, pTo, pApplyID, pFormNo, pFormSno, pStep, pType})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginSend(ByVal pFrom As String, ByVal pTo As String, ByVal pApplyID As String, ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pStep As Integer, ByVal pType As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Send", New Object() {pFrom, pTo, pApplyID, pFormNo, pFormSno, pStep, pType}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSend(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNextGate", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetNextGate(ByVal pFormNo As String, ByVal pStep As Integer, ByVal pUserID As String, ByVal pApplyID As String, ByVal pAgentID As String, ByVal pAllocateID As String, ByVal pMultiJob As Integer, ByRef pNextStep As Integer, ByRef pNextGate() As String, ByRef pAgentGate() As String, ByRef pCount As Integer, ByRef pFlowType As Integer, ByVal pAction As Integer) As Integer
            Dim results() As Object = Me.Invoke("GetNextGate", New Object() {pFormNo, pStep, pUserID, pApplyID, pAgentID, pAllocateID, pMultiJob, pNextStep, pNextGate, pAgentGate, pCount, pFlowType, pAction})
            pNextStep = CType(results(1),Integer)
            pNextGate = CType(results(2),String())
            pAgentGate = CType(results(3),String())
            pCount = CType(results(4),Integer)
            pFlowType = CType(results(5),Integer)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetNextGate(ByVal pFormNo As String, ByVal pStep As Integer, ByVal pUserID As String, ByVal pApplyID As String, ByVal pAgentID As String, ByVal pAllocateID As String, ByVal pMultiJob As Integer, ByVal pNextStep As Integer, ByVal pNextGate() As String, ByVal pAgentGate() As String, ByVal pCount As Integer, ByVal pFlowType As Integer, ByVal pAction As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetNextGate", New Object() {pFormNo, pStep, pUserID, pApplyID, pAgentID, pAllocateID, pMultiJob, pNextStep, pNextGate, pAgentGate, pCount, pFlowType, pAction}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetNextGate(ByVal asyncResult As System.IAsyncResult, ByRef pNextStep As Integer, ByRef pNextGate() As String, ByRef pAgentGate() As String, ByRef pCount As Integer, ByRef pFlowType As Integer) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            pNextStep = CType(results(1),Integer)
            pNextGate = CType(results(2),String())
            pAgentGate = CType(results(3),String())
            pCount = CType(results(4),Integer)
            pFlowType = CType(results(5),Integer)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMainJobID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMainJobID(ByVal pUser As String) As String
            Dim results() As Object = Me.Invoke("GetMainJobID", New Object() {pUser})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetMainJobID(ByVal pUser As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMainJobID", New Object() {pUser}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetMainJobID(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAgentID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAgentID(ByVal pFormNo As String, ByVal pUser As String, ByVal pNowDateTime As String) As String
            Dim results() As Object = Me.Invoke("GetAgentID", New Object() {pFormNo, pUser, pNowDateTime})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetAgentID(ByVal pFormNo As String, ByVal pUser As String, ByVal pNowDateTime As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAgentID", New Object() {pFormNo, pUser, pNowDateTime}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAgentID(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFormSeqNo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFormSeqNo(ByVal pFormNo As String, ByRef pSeqNo As Integer) As Integer
            Dim results() As Object = Me.Invoke("GetFormSeqNo", New Object() {pFormNo, pSeqNo})
            pSeqNo = CType(results(1),Integer)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetFormSeqNo(ByVal pFormNo As String, ByVal pSeqNo As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetFormSeqNo", New Object() {pFormNo, pSeqNo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetFormSeqNo(ByVal asyncResult As System.IAsyncResult, ByRef pSeqNo As Integer) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            pSeqNo = CType(results(1),Integer)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFieldAttribute", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFieldAttribute(ByVal pFormNo As String, ByVal pStep As Integer, ByRef pFieldName() As String, ByRef pAttribute() As Integer) As Integer
            Dim results() As Object = Me.Invoke("GetFieldAttribute", New Object() {pFormNo, pStep, pFieldName, pAttribute})
            pFieldName = CType(results(1),String())
            pAttribute = CType(results(2),Integer())
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetFieldAttribute(ByVal pFormNo As String, ByVal pStep As Integer, ByVal pFieldName() As String, ByVal pAttribute() As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetFieldAttribute", New Object() {pFormNo, pStep, pFieldName, pAttribute}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetFieldAttribute(ByVal asyncResult As System.IAsyncResult, ByRef pFieldName() As String, ByRef pAttribute() As Integer) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            pFieldName = CType(results(1),String())
            pAttribute = CType(results(2),Integer())
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CommissionNo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CommissionNo(ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pStep As Integer, ByVal pNo As String) As Integer
            Dim results() As Object = Me.Invoke("CommissionNo", New Object() {pFormNo, pFormSno, pStep, pNo})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginCommissionNo(ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pStep As Integer, ByVal pNo As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CommissionNo", New Object() {pFormNo, pFormSno, pStep, pNo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCommissionNo(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOPLeadTime", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOPLeadTime(ByVal pFormNo As String, ByVal pStep As Integer, ByVal pLevel As String) As Integer
            Dim results() As Object = Me.Invoke("GetOPLeadTime", New Object() {pFormNo, pStep, pLevel})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetOPLeadTime(ByVal pFormNo As String, ByVal pStep As Integer, ByVal pLevel As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetOPLeadTime", New Object() {pFormNo, pStep, pLevel}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetOPLeadTime(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSystemData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSystemData(ByVal pCat As String, ByVal pDKey As String) As String
            Dim results() As Object = Me.Invoke("GetSystemData", New Object() {pCat, pDKey})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetSystemData(ByVal pCat As String, ByVal pDKey As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetSystemData", New Object() {pCat, pDKey}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetSystemData(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetQCLeadTime", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetQCLeadTime(ByVal pFormNo As String, ByVal pStep As Integer) As Integer
            Dim results() As Object = Me.Invoke("GetQCLeadTime", New Object() {pFormNo, pStep})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetQCLeadTime(ByVal pFormNo As String, ByVal pStep As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetQCLeadTime", New Object() {pFormNo, pStep}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetQCLeadTime(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTableName", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTableName(ByVal pFormNo As String) As String
            Dim results() As Object = Me.Invoke("GetTableName", New Object() {pFormNo})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetTableName(ByVal pFormNo As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTableName", New Object() {pFormNo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTableName(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserName", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserName(ByVal pUser As String) As String
            Dim results() As Object = Me.Invoke("GetUserName", New Object() {pUser})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetUserName(ByVal pUser As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUserName", New Object() {pUser}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetUserName(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserID(ByVal pUserName As String) As String
            Dim results() As Object = Me.Invoke("GetUserID", New Object() {pUserName})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetUserID(ByVal pUserName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUserID", New Object() {pUserName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetUserID(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCalendarGroup", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCalendarGroup(ByVal pUser As String) As String
            Dim results() As Object = Me.Invoke("GetCalendarGroup", New Object() {pUser})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetCalendarGroup(ByVal pUser As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetCalendarGroup", New Object() {pUser}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetCalendarGroup(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWorkID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetWorkID(ByVal pUser As String) As String
            Dim results() As Object = Me.Invoke("GetWorkID", New Object() {pUser})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetWorkID(ByVal pUser As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetWorkID", New Object() {pUser}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetWorkID(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSignType", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSignType(ByVal pFormNo As String, ByVal pStep As Integer) As Integer
            Dim results() As Object = Me.Invoke("GetSignType", New Object() {pFormNo, pStep})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetSignType(ByVal pFormNo As String, ByVal pStep As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetSignType", New Object() {pFormNo, pStep}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetSignType(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFlowType", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFlowType(ByVal pFormNo As String, ByVal pStep As Integer) As Integer
            Dim results() As Object = Me.Invoke("GetFlowType", New Object() {pFormNo, pStep})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetFlowType(ByVal pFormNo As String, ByVal pStep As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetFlowType", New Object() {pFormNo, pStep}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetFlowType(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApplyTime", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetApplyTime(ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pNowDateTime As String) As String
            Dim results() As Object = Me.Invoke("GetApplyTime", New Object() {pFormNo, pFormSno, pNowDateTime})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetApplyTime(ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pNowDateTime As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetApplyTime", New Object() {pFormNo, pFormSno, pNowDateTime}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetApplyTime(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDecideHistory", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDecideHistory(ByVal pFormNo As String, ByVal pFormSno As Integer) As String
            Dim results() As Object = Me.Invoke("GetDecideHistory", New Object() {pFormNo, pFormSno})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetDecideHistory(ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetDecideHistory", New Object() {pFormNo, pFormSno}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetDecideHistory(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WriteWaitCheck", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WriteWaitCheck(ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pNowDateTime As String) As Integer
            Dim results() As Object = Me.Invoke("WriteWaitCheck", New Object() {pFormNo, pFormSno, pNowDateTime})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginWriteWaitCheck(ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pNowDateTime As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("WriteWaitCheck", New Object() {pFormNo, pFormSno, pNowDateTime}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndWriteWaitCheck(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CanUseSheet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CanUseSheet(ByVal pFormNo As String, ByVal pUserID As String) As Integer
            Dim results() As Object = Me.Invoke("CanUseSheet", New Object() {pFormNo, pUserID})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginCanUseSheet(ByVal pFormNo As String, ByVal pUserID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CanUseSheet", New Object() {pFormNo, pUserID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCanUseSheet(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFlowLoading", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFlowLoading(ByVal pFormNo As String, ByVal pStep As Integer) As Integer
            Dim results() As Object = Me.Invoke("GetFlowLoading", New Object() {pFormNo, pStep})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetFlowLoading(ByVal pFormNo As String, ByVal pStep As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetFlowLoading", New Object() {pFormNo, pStep}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetFlowLoading(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNextAction", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetNextAction(ByVal pFormNo As String, ByVal pStep As Integer) As Integer
            Dim results() As Object = Me.Invoke("GetNextAction", New Object() {pFormNo, pStep})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetNextAction(ByVal pFormNo As String, ByVal pStep As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetNextAction", New Object() {pFormNo, pStep}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetNextAction(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ArrangFlowControl", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ArrangFlowControl(ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pStep As Integer, ByVal pLevel As String, ByVal pApplyID As String, ByVal pUserID As String, ByVal pAllocateID As String, ByVal pAction As Integer, ByRef pNextStep As Integer) As Integer
            Dim results() As Object = Me.Invoke("ArrangFlowControl", New Object() {pFormNo, pFormSno, pStep, pLevel, pApplyID, pUserID, pAllocateID, pAction, pNextStep})
            pNextStep = CType(results(1),Integer)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginArrangFlowControl(ByVal pFormNo As String, ByVal pFormSno As Integer, ByVal pStep As Integer, ByVal pLevel As String, ByVal pApplyID As String, ByVal pUserID As String, ByVal pAllocateID As String, ByVal pAction As Integer, ByVal pNextStep As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ArrangFlowControl", New Object() {pFormNo, pFormSno, pStep, pLevel, pApplyID, pUserID, pAllocateID, pAction, pNextStep}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndArrangFlowControl(ByVal asyncResult As System.IAsyncResult, ByRef pNextStep As Integer) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            pNextStep = CType(results(1),Integer)
            Return CType(results(0),Integer)
        End Function
    End Class
End Namespace
